### PR TITLE
Bugfix/kbdev 1158 investigating gkb clinicaltrial org loader errors

### PR DESCRIPTION
**Pull request by sshugsc**
update clinical trial loader to use the new clinicaltrial.org api

### CODE REVIEW

**Comment by mathieulemieux** [comment]
@sshugsc , please post on the ticket the new log you're getting and add a link in the description. Also, check in the log if everything looks ok. I'll duplicate here a question I posted on KBDEV-1158 so we don't loose track: is it loading all the trials, only the newer ones, or the user can choose at run time?

**Review by mathieulemieux — CHANGES_REQUESTED** [review]
Two major problems here:

- In the log file, we can see {"error":0,"success":1000} and "ClinicalTrial":{"created":213}, with 622 warn messages; are we sure these 1000 records are actually as many succes? What is happening to the ClinicalTrial record whan a Disease term is not found?

- There is ~500k CT at clinicaltrials.gov, and ~70k in GKB prod, so we should be loading much more than 1000, unless we are only uploading the last 2 weeks, but then, why 1000 records? @sshugsc, can you please find how many records we should usually get?

Related:

- Apparently, the old API used here https://github.com/bcgsc/pori_graphkb_loader/blob/e3778a623fc379efadb74fa34b9eec2d03ce8e5b/src/clinicaltrialsgov/index.js#L341-L353 is not working as intended. Dosumentation about these fields is needed. @sshugsc , maybe by looking on the website, by asking via email, or by pigning @creisle ?

**Comment by creisle** [comment]
> There is ~500k CT at clinicaltrials.gov, and ~70k in GKB prod, so we should be loading much more than 1000, unless we are only uploading the last 2 weeks, but then, why 1000 records? @sshugsc, can you please find how many records we should usually get?

Most of the trials are not cancer-relevant. Its been a long time but I believe we only load cancer-related trials

**Comment by mathieulemieux** [comment]
Ty @creisle for the link and explanations; I knew we were filtering the records but it's nice to have more context. The http request has a "count=10000" but something is limiting the results to 1000. @sshugsc , maybe there is pagination now?

**Comment by sshugsc** [comment]
> Ty @creisle for the link and explanations; I knew we were filtering the records but it's nice to have more context. The http request has a "count=10000" but something is limiting the results to 1000. @sshugsc , maybe there is pagination now?

Thank you @creisle for the explanations! @mathieulemieux yes, there is a pageSize limit to 1000 mentioned on their web [https://clinicaltrials.gov/data-api/api](https://clinicaltrials.gov/data-api/api) . 

> @sshugsc , please post on the ticket the new log you're getting and add a link in the description. Also, check in the log if everything looks ok. I'll duplicate here a question I posted on KBDEV-1158 so we don't loose track: is it loading all the trials, only the newer ones, or the user can choose at run time?

Discussed with @elewis2 , planned to keep this PR stick to load all the trials (after filters) with clinicaltrial.gov api. @mathieulemieux New commit is pushed, ready for review.

**Review by mathieulemieux — APPROVED** [review]
Bravo!

**Pull request merged**
